# Notebook 6 – Data Inspection

## head()

The head() method is used to display the first few rows of a DataFrame or Series

By default, head() displays the first 5 rows. You can specify how many rows you want to display.

Why do we use head()?

- To see the beginning of a dataset.
- To check whether a CSV or Excel file was loaded correctly.
- To understand the columns and values in a dataset.
- To inspect data before performing analysis.
- To preview datasets before building machine learning models.

Syntax:

DataFrame.head(n)


DataFrame - You want to inspect

head() — displays the first 5 rows

head(n) — displays the first n rows

In [1]:
import pandas as pd                     #Example

data = {
    "Name": ["Ajay", "Vijay", "Vicky", "Ram", "Priya", "Kiran"],
    "Age": [25, 22, 24, 28, 23, 26],
    "Salary": [25000, 20000, 30000, 40000, 28000, 35000]
}

df = pd.DataFrame(data)

df.head()

    Name  Age  Salary
0   Ajay   25   25000
1  Vijay   22   20000
2  Vicky   24   30000
3    Ram   28   40000
4  Priya   23   28000

In [ ]:
Notice that the sixth row, Kiran, is not displayed

In [2]:
df.head(3)

    Name  Age  Salary
0   Ajay   25   25000
1  Vijay   22   20000
2  Vicky   24   30000

## tail()

The tail() method in Pandas is used to display the last few rows of a DataFrame or Series

By default, tail() displays the last 5 rows. You can specify the number of rows you want to display

Why do we use tail()?

- To see the last rows of a dataset.
- To check whether data was loaded correctly from a CSV or Excel file.
- To inspect the latest records in a dataset.
- To verify the results after adding or sorting data.
- To inspect data before performing data analysis or machine learning.

Syntax:

DataFrame.tail(n)


DataFrame — the Pandas DataFrame you want to inspect.

tail() — the method that returns the last rows

n — the number of rows to display; the default is 5.

In [3]:
import pandas as pd                #Example

data = {
    "Name": ["Ravi", "Raju", "Sita", "Ram", "Priya", "Kiran"],
    "Age": [25, 22, 24, 28, 23, 26],
    "Salary": [25000, 20000, 30000, 40000, 28000, 35000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Salary
0   Ravi   25   25000
1   Raju   22   20000
2   Sita   24   30000
3    Ram   28   40000
4  Priya   23   28000
5  Kiran   26   35000

In [7]:
df.tail()

    Name  Age  Salary
1   Raju   22   20000
2   Sita   24   30000
3    Ram   28   40000
4  Priya   23   28000
5  Kiran   26   35000

In [ ]:
Explanation:

1. df refers to our employee DataFrame.
2. tail() selects rows from the end of the DataFrame.
3. Because we didn't specify a number, Pandas selects the last 5 rows.
4. The original index values are preserved, so the output starts at index 1.
    
Important: tail() does not delete the other rows. It only returns a view of the last few rows for display; the DataFrame itself remains unchanged

## sample()


The sample() method is used to select random rows or columns from a DataFrame or Series

Unlike head(), which selects rows from the beginning, sample() selects rows randomly

Why do we use sample()?

- To select random records from a dataset.
- To inspect a dataset without always looking at the first rows.
- To create a small sample for data analysis.
- To select random customers or transactions.
- To create random subsets of data for machine learning experiments.

Syntax:

DataFrame.sample(
    n=None,
    frac=None,
    replace=False,
    random_state=None,
    axis=0
)


Parameter	       Meaning


n	              Number of random rows or columns to select


frac	         Fraction of the dataset to select


replace       	 Whether the same row can be selected more than once


random_state	Seed for reproducible random selection


axis=0	        Select rows; this is the default


axis=1	        Select columns

Real-world and AI/ML applications:

Business example: A company has 100,000 customer records. It can use sample(n=100) to inspect 100 randomly selected customers instead of viewing the entire dataset.

AI/ML example: You can select a reproducible subset of records to test a data-cleaning or preprocessing workflow before applying it to a larger dataset.

For an actual machine learning train/test split, sklearn.model_selection.train_test_split() is often more appropriate because it separates data into training and testing sets.

In [8]:
import pandas as pd

data = {
    "Name": ["Ravi", "Raju", "Sita", "Ram", "Priya", "Kiran"],
    "Age": [25, 22, 24, 28, 23, 26],
    "Salary": [25000, 20000, 30000, 40000, 28000, 35000]
}

df = pd.DataFrame(data)

df

    Name  Age  Salary
0   Ravi   25   25000
1   Raju   22   20000
2   Sita   24   30000
3    Ram   28   40000
4  Priya   23   28000
5  Kiran   26   35000

In [9]:
df.sample()

    Name  Age  Salary
5  Kiran   26   35000

In [ ]:
Explanation:
1. df refers to the employee DataFrame.
2. sample() randomly selects a row.
3. By default, it selects one row.
4. The original DataFrame is not modified.

## info()

In [ ]:
In Pandas, the info() method is used to display a summary of a DataFrame, including the number of rows, column names, data types, non-null values, and memory usage
    
It helps you understand the structure of a dataset before performing data analysis or machine learning

Why do we use info()?

- To check the number of rows and columns.
- To identify column names.
- To understand data types such as int64, float64, and object.
- To identify missing values by checking non-null counts.
- To check how much memory a DataFrame uses.
- To inspect data before cleaning or building a machine learning model.

 Syntax:


DataFrame.info(
    verbose=None,
    buf=None,
    max_cols=None,
    memory_usage=None,
    show_counts=None
)

In [11]:
import pandas as pd                           #Example

data = {
    "Name": ["Ravi", "Raju", "Sita", "Ram", None, "Kiran"],
    "Age": [25, 22, 24, 28, 23, 26],
    "Salary": [25000, 20000, 30000, 40000, 28000, 35000]
}

df = pd.DataFrame(data)

df

    Name  Age  Salary
0   Ravi   25   25000
1   Raju   22   20000
2   Sita   24   30000
3    Ram   28   40000
4    NaN   23   28000
5  Kiran   26   35000

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     6 non-null      int64
 2   Salary  6 non-null      int64
dtypes: int64(2), str(1)
memory usage: 297.0 bytes

## describe()

In [ ]:
The Pandas describe() function is used to generate summary statistics for a DataFrame or Series

It helps us quickly understand numerical data by calculating:
    
- Count
- Mean (average)
- Standard deviation
- Minimum value
- 25th percentile
- 50th percentile (median)
- 75th percentile
- Maximum value
    
Syntax:

    df.describe()

In [13]:
import pandas as pd                        #Example

data = {
    "Name": ["Ravi", "Raju", "Sita", "Ram", None, "Kiran"],
    "Age": [25, 22, 24, 28, 23, 26],
    "Salary": [25000, 20000, 30000, 40000, 28000, 35000]
}

df = pd.DataFrame(data)

df

    Name  Age  Salary
0   Ravi   25   25000
1   Raju   22   20000
2   Sita   24   30000
3    Ram   28   40000
4    NaN   23   28000
5  Kiran   26   35000

In [14]:
df.describe()

             Age        Salary
count   6.000000      6.000000
mean   24.666667  29666.666667
std     2.160247   7118.052168
min    22.000000  20000.000000
25%    23.250000  25750.000000
50%    24.500000  29000.000000
75%    25.750000  33750.000000
max    28.000000  40000.000000

Understanding each statistic:
    
1. count
    
Counts the number of non-missing values in each column.
    
df.describe().loc["count"]

Output:

Age         6.0
Salary      6.0


Meaning: There are six available age values and six salary values.
    
2. mean
Calculates the average value.
Formula:
\[
\text{Mean}=\frac{\text{Sum of values}}{\text{Number of values}}
\]

For Age:
\[
\frac{25+22+24+28+23+26}{6}=24.67
\]

Output: The average age is approximately 24.67 years.
    
3. std

Standard deviation measures how spread out the values are around their mean.
    
- Smaller standard deviation: values are closer to the mean.
    
- Larger standard deviation: values are more spread out.
    
df["Salary"].std()

Output:
7031.67

This indicates that salaries have a standard deviation of approximately ₹7,032.
    
4. min

Returns the smallest value.
    
df["Salary"].min()

Output:
20000


The minimum salary is ₹20,000.
    
5. 25% — First quartile (Q1)
    
The value below which approximately 25% of the observations fall.
    
For Age:
23.25


6. 50% — Median (Q2)
    
The middle value of the data, also called the 50th percentile.
    
For Age:
24.5


This means the median age is 24.5 years.
    
7. 75% — Third quartile (Q3)
    
The value below which approximately 75% of the observations fall.
    
For Age:
25.75


8. max
    
Returns the largest value.
    
df["Salary"].max()

Output:
40000


The maximum salary is ₹40,000.
    
5. Important variations of describe()
    
A. Describe a single column
    
df["Age"].describe()


This produces summary statistics only for the Age column.
    
B. Include text columns
    
df.describe(include="all")

This includes both numerical and categorical columns where applicable.
For the Name column, you may see:
- count: number of non-missing names
- unique: number of distinct names
- top: most frequent name
- freq: frequency of the most common name
For example, if Ravi appears three times, top would be Ravi and freq would be 3.
    
C. Describe only categorical columns

df.describe(include=["object"])

This summarizes text columns such as Name.
    
D. Describe a CSV file

import pandas as pddf = pd.read_csv("employees.csv")df.describe()



This calculates statistics for numerical columns in your CSV file.
    
Make sure employees.csv is in the notebook's current working directory, or provide its correct file path.

6. Real-world applications

Business analytics
Quickly understand average employee salaries, minimum and maximum salaries, and salary variation

AI/ML data analysis
Check numerical features before training a model. For example, inspect customer ages, income, or house price

## shape

In [ ]:
The shape attribute is used to find the number of rows and columns in a Pandas DataFrame

Syntax:

dataframe.shape

Real-world applications:
    
- Business analytics: Find the number of customer records and customer features
- Data cleaning: Check whether the dataset has the expected dimensions before and after removing rows.
- AI/ML: Check the number of observations and input features before training a model.

In [15]:
import pandas as pd                           #Example

data = {
    "Name": ["Ravi", "Raju", "Sita", "Ram", "Kiran"],
    "Age": [25, 22, 24, 28, 26],
    "Salary": [25000, 20000, 30000, 40000, 35000]
}

df = pd.DataFrame(data)

df

    Name  Age  Salary
0   Ravi   25   25000
1   Raju   22   20000
2   Sita   24   30000
3    Ram   28   40000
4  Kiran   26   35000

In [16]:
df.shape

(5, 3)

In [ ]:
Explanation:

- 5 means there are 5 rows.
- 3 means there are 3 columns.

## Columns

The columns attribute in Pandas is used to display or retrieve the column names of a DataFrame

For example, if a DataFrame contains Name, Age, and Salary, the columns attribute returns those column labels

Syntax:

df.columns

columns is an attribute, not a function. Do not use parentheses like df.columns()


Real-world applications:

- Business analytics: Identify customer, sales, or employee fields in a dataset.
- Data cleaning: Rename unclear column names to meaningful names.
- AI/ML: Select the feature columns required for model training.
- CSV files: Check the column names after importing a dataset.

In [17]:
import pandas as pd                     #Example

data = {
    "Name": ["Ajay", "Vijay", "Vicky", "Ram", "Kiran"],
    "Age": [25, 22, 24, 28, 26],
    "Salary": [25000, 20000, 30000, 40000, 35000]
}

df = pd.DataFrame(data)

df

    Name  Age  Salary
0   Ajay   25   25000
1  Vijay   22   20000
2  Vicky   24   30000
3    Ram   28   40000
4  Kiran   26   35000

In [18]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [ ]:
Explanation:

- Name — first column
- Age — second column
- Salary — third column
- Index — Pandas object that stores the column labels.

## dtypes

In [ ]:
The dtypes attribute is used to identify the data type of each column in a Pandas DataFrame

It helps us understand what kind of data each column contains, such as text, integers, decimal numbers, or Boolean values

Syntax:

df.dtypes

Real-world applications:
    
- Business analytics: Check whether sales and revenue columns are numerical.
- Data cleaning: Identify columns that were accidentally imported as text.
- AI/ML: Ensure numerical features have appropriate types before model training.
- Date analysis: Convert date columns to datetime before calculating durations or grouping by month.

In [19]:
import pandas as pd                    #Example

data = {
    "Name": ["Vijay", "Raju", "Sita", "Ram"],
    "Age": [25, 22, 24, 28],
    "Salary": [25000.50, 20000.00, 30000.75, 40000.00],
    "Working": [True, True, False, True]
}

df = pd.DataFrame(data)

df

    Name  Age    Salary  Working
0  Vijay   25  25000.50     True
1   Raju   22  20000.00     True
2   Sita   24  30000.75    False
3    Ram   28  40000.00     True

In [20]:
df.dtypes

Name           str
Age          int64
Salary     float64
Working       bool
dtype: object

## memory_usage()

In [ ]:
The memory_usage() method is used to check how much computer memory each column in a Pandas DataFrame uses

It is useful when working with large datasets in data analysis and machine learning

Syntax:

df.memory_usage()

Real-world applications:
    
- Large datasets: Identify columns that consume substantial memory.
- Data cleaning: Check whether text columns use more memory than expected.
- AI/ML: Reduce memory requirements when processing large training datasets.
- Performance optimization: Consider more memory-efficient data types where appropriate.

In [21]:
import pandas as pd                     #Example

data = {
    "Name": ["Ravi", "Ajay", "Sita", "Ram"],
    "Age": [25, 22, 24, 28],
    "Salary": [25000, 20000, 30000, 40000]
}

df = pd.DataFrame(data)

df

   Name  Age  Salary
0  Ravi   25   25000
1  Raju   22   20000
2  Sita   24   30000
3   Ram   28   40000

In [22]:
df.memory_usage()

Index     132
Name       47
Age        32
Salary     32
dtype: int64

## nunique()

In [ ]:
The nunique() method is used to count the number of unique (distinct) values in a Pandas Series or DataFrame

If a column contains repeated values, nunique() counts each different value only once

Syntax:

df.nunique()

For Single Column:

df["column_name"].nunique()

By default, nunique() does not count missing values (NaN)

Real-world applications:
    
Business analytics
Count the number of different customers, cities, product categories, or departments in a dataset

AI/ML data preparation
Identify how many distinct categories exist in a feature before encoding categorical data for machine learning.
    
Inventory analysis
Count distinct product types or prices in an inventory dataset.

In [23]:
import pandas as pd                    #Example

data = {
    "Name": ["Ravi", "Raju", "Ravi", "Sita", "Ajay", "Kiran"],
    "Age": [25, 22, 25, 24, 22, 26],
    "Department": ["IT", "HR", "IT", "Sales", "HR", "IT"]
}

df = pd.DataFrame(data)

df

    Name  Age Department
0   Ravi   25         IT
1   Raju   22         HR
2   Ravi   25         IT
3   Sita   24      Sales
4   Ajay   22         HR
5  Kiran   26         IT

In [24]:
df.nunique()

Name          5
Age           4
Department    3
dtype: int64

In [ ]:
Explanation:

Column	Unique count	Unique values
Name	    4	             Ravi, Raju, Sita, Kiran
Age	        4	             25, 22, 24, 26
Department	3	             IT, HR, Sales

The dataset has six rows, but only four distinct names and three distinct departments

In [25]:
df["Department"].nunique()

3

## value_counts()

In [ ]:
The value_counts() method is used to count how many times each unique value appears in a column or Series

It is useful for understanding which values occur most frequently in a dataset

For example, if a Department column contains IT, HR, IT, Sales, IT, then IT appears 3 times, HR appears once, and Sales appears once

Syntax:

df["column_name"].value_counts()

value_counts() is a method, so it uses parentheses

Real-world applications:

Business analytics
Count orders by payment method, sales by product category, or employees by department.

AI/ML data preparation
Check how frequently each class appears in a classification dataset, such as positive versus negative predictions or labels.

Inventory analysis
Identify the most frequently occurring products or categories in sales records.

In [26]:
import pandas as pd

data = {
    "Name": ["Ravi", "Raju", "Sita", "Ram", "Kiran", "Arun"],
    "Department": ["IT", "HR", "IT", "Sales", "IT", "HR"],
    "Age": [25, 22, 24, 28, 26, 23]
}

df = pd.DataFrame(data)

df

    Name Department  Age
0   Ravi         IT   25
1   Raju         HR   22
2   Sita         IT   24
3    Ram      Sales   28
4  Kiran         IT   26
5   Arun         HR   23

In [27]:
df["Department"].value_counts()

Department
IT       3
HR       2
Sales    1
Name: count, dtype: int64

In [ ]:
Explanation:

Department	Count
  IT	         3
  HR	         2

  Sales	1
- IT appears 3 times
- HR appears 2 times
- Sales appears 1 time
    
By default, the results are sorted from the most frequent value to the least frequent value.