# Notebook 7 – Selecting & Filtering Data

## loc

loc[] is an indexer used to select, access, filter, and modify rows and columns using their labels

It is useful when working with datasets such as employee records, student marks, sales reports, customer details, and AI/ML datasets

Syntax:

DataFrame.loc[row_label, column_label]

DataFrame — the table containing your data.

row_label — the label of the row you want to select.

column_label — the name of the column you want to select

ou can select a single row, multiple rows, specific columns, or rows that satisfy a condition

Real-world and AI/ML applications:

- Employee analysis: Select employees whose salaries exceed a threshold.
- Sales analysis: Filter sales from a specific city or date.
- Data cleaning: Locate and update missing or incorrect values.
- Machine learning: Select records that meet criteria before preparing a dataset for model training.
- Feature selection: Extract particular columns for model inputs.

In [1]:
import pandas as pd                      #Example

data = {
    "Name": ["Sai", "Raju", "Bunny", "Anu", "Vijay"],
    "Age": [25, 30, 22, 28, 35],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Hyderabad", "Mumbai"],
    "Salary": [25000, 35000, 30000, 40000, 50000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age       City  Salary
0    Sai   25  Hyderabad   25000
1   Raju   30    Chennai   35000
2  Bunny   22  Bangalore   30000
3    Anu   28  Hyderabad   40000
4  Vijay   35     Mumbai   50000

In [2]:
df.loc[0]               #To retrieve a Complete row

Name            Sai
Age              25
City      Hyderabad
Salary        25000
Name: 0, dtype: object

In [ ]:
Explanation:

- df refers to our DataFrame.
- .loc[0] selects the row whose label is 0.
- The output contains all values from that row.
- The result is a Pandas Series rather than a DataFrame.

In [3]:
df.loc[2]           #To retrieve loc 2

Name          Bunny
Age              22
City      Bangalore
Salary        30000
Name: 2, dtype: object

In [4]:
df.loc[0, "Name"]              #Specific value

'Sai'

In [5]:
print(df.loc[0, "Salary"])     #To select Specific Column from a row

25000

In [6]:
df.loc[[0, 2, 4]]                #Multiple locs

    Name  Age       City  Salary
0    Sai   25  Hyderabad   25000
2  Bunny   22  Bangalore   30000
4  Vijay   35     Mumbai   50000

In [7]:
df.loc[1:3]                   #Range

    Name  Age       City  Salary
1   Raju   30    Chennai   35000
2  Bunny   22  Bangalore   30000
3    Anu   28  Hyderabad   40000

In [8]:
df.loc[(df["Age"] > 25) & (df["Salary"] > 30000)]          #Filter Using Multiple conditions

    Name  Age       City  Salary
1   Raju   30    Chennai   35000
3    Anu   28  Hyderabad   40000
4  Vijay   35     Mumbai   50000

## iloc

iloc[] stands for Integer Location. It is used to select rows and columns from a DataFrame based on their integer positions

Unlike loc[], which uses row labels and column names, iloc[] uses zero-based integer positions.

For example:

- Position 0 means the first row or column.
- Position 1 means the second row or column.
- Position 2 means the third row or column.

Syntax:

DataFrame.iloc[row_position, column_position]

You can use iloc[] to:

- Select a single row.
- Select a single value.
- Select multiple rows or columns.
- Select a range of rows or columns.
- Filter data indirectly by using row positions.
- Update values at specific positions.
  
Real-world and AI/ML applications:

- Employee analysis: Select employees whose salaries exceed a threshold.
- Sales analysis: Filter sales from a specific city or date.
- Data cleaning: Locate and update missing or incorrect values.
- Machine learning: Select records that meet criteria before preparing a dataset for model training.
- Feature selection: Extract particular columns for model inputs.

In [9]:
import pandas as pd                 #Example

data = {
    "Name": ["Vijay", "Raju", "Bunny", "Anu", "Kiran"],
    "Age": [25, 30, 22, 28, 35],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Hyderabad", "Mumbai"],
    "Salary": [25000, 35000, 30000, 40000, 50000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age       City  Salary
0  Vijay   25  Hyderabad   25000
1   Raju   30    Chennai   35000
2  Bunny   22  Bangalore   30000
3    Anu   28  Hyderabad   40000
4  Kiran   35     Mumbai   50000

In [10]:
print(df.iloc[0])

Name          Vijay
Age              25
City      Hyderabad
Salary        25000
Name: 0, dtype: object

In [ ]:
Explanation:

- df refers to the DataFrame.
- .iloc[0] selects the first row.
- The result contains all four column values.
- The result is a Pandas Series.

In [11]:
print(df.iloc[0:3, 0:2])           #select rows ans Columns Together

    Name  Age
0  Vijay   25
1   Raju   30
2  Bunny   22

In [12]:
print(df.iloc[[0, 2, 4]])               #Multiple rows

    Name  Age       City  Salary
0  Vijay   25  Hyderabad   25000
2  Bunny   22  Bangalore   30000
4  Kiran   35     Mumbai   50000

In [13]:
print(df.iloc[:, [0, 1]])             #Multiple Columns

    Name  Age
0  Vijay   25
1   Raju   30
2  Bunny   22
3    Anu   28
4  Kiran   35

In [14]:
print(df.iloc[[0, -1]])            #First and Last rows

    Name  Age       City  Salary
0  Vijay   25  Hyderabad   25000
4  Kiran   35     Mumbai   50000

## Boolean Indexing

Boolean Indexing in Pandas is a technique used to select rows or values from a DataFrame or Series based on conditions that evaluate to True or False

It is especially useful for filtering datasets in data analysis, data cleaning, business reporting, and machine learning

For example, imagine you have employee salary data and want to find employees earning more than ₹30,000. Boolean indexing allows you to select only those employees.

How Boolean Indexing works:

Boolean indexing follows three steps:

1. Write a condition.
2. Pandas evaluates the condition for every row and returns True or False.
3. Use that Boolean result to select the rows where the condition is True.

Applications in Data Science and AI/ML:

- Data cleaning: Find invalid or missing values.
- Business analysis: Identify high-value customers or high-salary employees.
- Sales analysis: Select transactions above a target amount.
- Machine learning: Filter records before training or evaluating models.
- Exploratory data analysis: Investigate patterns in specific subsets of data.

In [15]:
import pandas as pd                     #Example

data = {
    "Name": ["Ravi", "Raju", "Priya", "Anu", "Kiran"],
    "Age": [25, 30, 22, 28, 35],
    "Salary": [25000, 35000, 30000, 40000, 50000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Salary
0   Ravi   25   25000
1   Raju   30   35000
2  Priya   22   30000
3    Anu   28   40000
4  Kiran   35   50000

In [16]:
print(df["Age"] > 25)         #Create a boolean Condition

0    False
1     True
2    False
3     True
4     True
Name: Age, dtype: bool

In [ ]:
Explanation:

- Ravi is 25, so the condition is False
- Raju is 30, so the condition is True
- Priya is 22, so the condition is False
- Anu is 28, so the condition is True
- Kiran is 35, so the condition is True

The result is a Boolean Series: one True or False value for each row

In [17]:
result = df[df["Age"] > 25]              #Select rows using boolean indexig

print(result)

    Name  Age  Salary
1   Raju   30   35000
3    Anu   28   40000
4  Kiran   35   50000

In [ ]:
How it works:
    
- df["Age"] > 25 creates a Boolean Series.
- df[...] uses that Series to filter the DataFrame.
- Only rows where the condition is True are returned.

## Filtering Rows

Row filtering in Pandas is the process of selecting only the rows that satisfy a particular condition from a DataFrame

It helps you find specific information without displaying the entire dataset

For example, suppose you have 1,000 employee records and want to find employees earning more than ₹30,000. Instead of viewing all 1,000 rows, you can filter and display only the matching employees

Row filtering is commonly used in:
- Data analysis
- Data cleaning
- Business reporting
- Sales analysis
- AI and machine learning

In [18]:
import pandas as pd

data = {
    "Name": ["Sai", "Vijay", "Ajay", "Bunny", "Kiran"],
    "Age": [25, 30, 22, 28, 35],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Hyderabad", "Mumbai"],
    "Salary": [25000, 35000, 30000, 40000, 50000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age       City  Salary
0    Sai   25  Hyderabad   25000
1  Vijay   30    Chennai   35000
2   Ajay   22  Bangalore   30000
3  Bunny   28  Hyderabad   40000
4  Kiran   35     Mumbai   50000

In [20]:
result = df[df["Age"] > 25]                    #Filtering employees Age > 25

print(result)

    Name  Age       City  Salary
1  Vijay   30    Chennai   35000
3  Bunny   28  Hyderabad   40000
4  Kiran   35     Mumbai   50000

In [ ]:
Explanation:

1. df["Age"] selects the Age column.
2. df["Age"] > 25 checks whether each employee is older than 25.
3. df[...] returns only the rows where the condition is True.
4. The filtered DataFrame contains Vijay, Bunny, and Kiran

In [21]:
result = df[                      #Using And Condition
    (df["Age"] > 25) &
    (df["Salary"] > 30000)
]

print(result)

    Name  Age       City  Salary
1  Vijay   30    Chennai   35000
3  Bunny   28  Hyderabad   40000
4  Kiran   35     Mumbai   50000

In [22]:
result = df[                          #OR Condition
    (df["Age"] < 25) |
    (df["Salary"] > 40000)
]

print(result)

    Name  Age       City  Salary
2   Ajay   22  Bangalore   30000
4  Kiran   35     Mumbai   50000

## query()

In [ ]:
The query() method in Pandas is used to filter rows from a DataFrame by writing conditions as a string expression

It provides a readable way to select rows without repeatedly writing the DataFrame name and square brackets

For example, suppose you have employee data and want to find employees whose salary is greater than ₹30,000. You can use query() to filter those employees

Syntax:

DataFrame.query("condition")

Here:

- DataFrame is the table containing your data
- query() is the method that filters the rows
- "condition" is a string containing the condition to evaluate

In [24]:
import pandas as pd                               #Example

data = {
    "Name": ["Ajay", "Vijay", "Priya", "Bunny", "Kiran"],
    "Age": [25, 30, 22, 28, 35],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Hyderabad", "Mumbai"],
    "Salary": [25000, 35000, 30000, 40000, 50000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age       City  Salary
0   Ajay   25  Hyderabad   25000
1  Vijay   30    Chennai   35000
2  Priya   22  Bangalore   30000
3  Bunny   28  Hyderabad   40000
4  Kiran   35     Mumbai   50000

In [25]:
result = df.query("Age > 25")                   #filtering rows

print(result)

    Name  Age       City  Salary
1  Vijay   30    Chennai   35000
3  Bunny   28  Hyderabad   40000
4  Kiran   35     Mumbai   50000

In [ ]:
Explanation:

1. df is the DataFrame.
2. .query() evaluates the condition inside the string
3. "Age > 25" checks which employees are older than 25
4. Only the matching rows are returned

## isin()

In [ ]:
The isin() method is used to check whether values in a Pandas Series or DataFrame belong to a specified list of values

It returns True when a value matches one of the specified values and False otherwise

Real-world example: Suppose you have employee data and want to find employees who live in either Hyderabad or Chennai. You can use isin() to filter those employees

Syntax:

Series.isin(values)

Series: The column you want to check
values: A list, set, tuple, or other collection of values to search for
Output: A Boolean Series containing True or False

In [26]:
import pandas as pd                            #Example

data = {
    "Name": ["Ravi", "Raju", "Priya", "Anu", "Kiran"],
    "Age": [25, 30, 22, 28, 35],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Hyderabad", "Mumbai"],
    "Salary": [25000, 35000, 30000, 40000, 50000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age       City  Salary
0   Ravi   25  Hyderabad   25000
1   Raju   30    Chennai   35000
2  Priya   22  Bangalore   30000
3    Anu   28  Hyderabad   40000
4  Kiran   35     Mumbai   50000

In [27]:
result = df[df["City"].isin(["Hyderabad", "Chennai"])]                      #FilteringEmployeesfromcities

print(result)

   Name  Age       City  Salary
0  Ravi   25  Hyderabad   25000
1  Raju   30    Chennai   35000
3   Anu   28  Hyderabad   40000

In [ ]:
Explanation:

1. df["City"] selects the City column.
2. .isin(["Hyderabad", "Chennai"]) checks which cities match.
3. df[...] keeps only the rows where the condition is True

In [28]:
result = df[df["Age"].isin([25, 30, 35])]                           #FilteringemployeesfrimAges

print(result)

    Name  Age       City  Salary
0   Ravi   25  Hyderabad   25000
1   Raju   30    Chennai   35000
4  Kiran   35     Mumbai   50000

## between()

The Pandas between() method is used to check whether values fall within a specified range

It returns True for values within the range and False for values outside the range
                                                      
Real-world example: Suppose you have employee data and want to select employees whose ages are between 25 and 30
    
Instead of writing two conditions, you can use between()


Syntax:

Series.between(left, right, inclusive="both")

Real-world and AI/ML applications:
    
- Business analytics: Find products priced between ₹500 and ₹1,000.
- Student analysis: Identify students scoring between 40 and 80 marks.
- Data cleaning: Find measurements outside an expected range by negating the condition with ~.
- Machine learning: Select records within a valid feature range before analysis.

In [29]:
import pandas as pd                           #Example

data = {
    "Name": ["Ajay", "Vijay", "Priya", "Anu", "Kiran"],
    "Age": [25, 30, 22, 28, 35],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Hyderabad", "Mumbai"],
    "Salary": [25000, 35000, 30000, 40000, 50000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age       City  Salary
0   Ajay   25  Hyderabad   25000
1  Vijay   30    Chennai   35000
2  Priya   22  Bangalore   30000
3    Anu   28  Hyderabad   40000
4  Kiran   35     Mumbai   50000

In [30]:
result = df[df["Age"].between(25, 30)]               #Filter employee by ages

print(result)

    Name  Age       City  Salary
0   Ajay   25  Hyderabad   25000
1  Vijay   30    Chennai   35000
3    Anu   28  Hyderabad   40000

## Sorting Data

Sorting data means arranging rows or values in a particular order, such as ascending or descending order

In Pandas, the two main sorting methods are:
    
- sort_values() — Sort data based on column values
- sort_index() — Sort data based on row index or column labels
    
Real-world example: Suppose you have employee records and want to arrange employees from the lowest salary to the highest salary. You can use sort_values()

In [31]:
import pandas as pd                              #Example

data = {
    "Name": ["Ajay", "Raju", "Vijay", "Anu", "Kiran"],
    "Age": [25, 30, 22, 28, 35],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Hyderabad", "Mumbai"],
    "Salary": [25000, 35000, 30000, 40000, 50000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age       City  Salary
0   Ajay   25  Hyderabad   25000
1   Raju   30    Chennai   35000
2  Vijay   22  Bangalore   30000
3    Anu   28  Hyderabad   40000
4  Kiran   35     Mumbai   50000

In [33]:
result = df.sort_values(by="Salary")                      #Sorting Salary in ascending order

print(result)

    Name  Age       City  Salary
0   Ajay   25  Hyderabad   25000
2  Vijay   22  Bangalore   30000
1   Raju   30    Chennai   35000
3    Anu   28  Hyderabad   40000
4  Kiran   35     Mumbai   50000

In [ ]:
Explanation:

1. df.sort_values(by="Salary") sorts rows using the Salary column.
2. By default, ascending=True.
3. The smallest salary appears first.
4. Notice that the original index labels remain unchanged

In [34]:
result = df.sort_values(by="Salary", ascending=False)               #Sorting Salary in Descending Order

print(result)

    Name  Age       City  Salary
4  Kiran   35     Mumbai   50000
3    Anu   28  Hyderabad   40000
1   Raju   30    Chennai   35000
2  Vijay   22  Bangalore   30000
0   Ajay   25  Hyderabad   25000

In [ ]:
Explanation:

- ascending=False sorts from highest to lowest.
- Kiran, who earns ₹50,000, appears first.
- Ravi, who earns ₹25,000, appears last.