# Notebook 10 – Combining Datasets

## concat()


The Pandas concat() function is used to combine two or more Series or DataFrames into a single object

For example, imagine you have employee data in two different DataFrames:

- DataFrame 1 contains employees from the IT department
- DataFrame 2 contains employees from the HR department
You can use pd.concat() to combine both DataFrames into one

Real-world applications:

- Combining monthly sales reports
- Merging customer records from different files
- Combining data collected from multiple branches
- Preparing datasets for data analysis and machine learning

Syntax:

pd.concat(
    objs,
    axis=0,
    join="outer",
    ignore_index=False
)


Parameter	       Meaning

objs	           The Series or DataFrames to combine
axis=0	           Combine vertically by adding rows; default
axis=1	           Combine horizontally by adding columns
join="outer"	   Keep all labels from both objects; default
join="inner"	   Keep only common labels along the other axis
ignore_index=True	Create a new sequential index for the result

Other options exist, but these are the most important ones to learn first

In [1]:
import pandas as pd                    #Example  

df1 = pd.DataFrame({
    "Name": ["Ravi", "Priya"],
    "Salary": [30000, 40000]
})

df2 = pd.DataFrame({
    "Name": ["Kiran", "Sneha"],
    "Salary": [50000, 45000]
})

print("DataFrame 1:")
print(df1)

print("\nDataFrame 2:")
print(df2)

DataFrame 1:
    Name  Salary
0   Ravi   30000
1  Priya   40000

DataFrame 2:
    Name  Salary
0  Kiran   50000
1  Sneha   45000

In [2]:
result = pd.concat([df1, df2])       #Combining two Data frames  Vertically

print(result)

    Name  Salary
0   Ravi   30000
1  Priya   40000
0  Kiran   50000
1  Sneha   45000

In [ ]:
Explanation:

- [df1, df2] is the list of DataFrames to combine
- axis=0 is the default, so rows are added vertically
- The original index labels are preserved by default

Notice that the index values 0 and 1 appear twice because both
DataFrames originally had those index labels

In [3]:
import pandas as pd             #Combining Data Frames Horizontally 

df1 = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Kiran"]
})

df2 = pd.DataFrame({
    "Salary": [30000, 40000, 50000]
})

result = pd.concat([df1, df2], axis=1)

print(result)

    Name  Salary
0   Ravi   30000
1  Priya   40000
2  Kiran   50000

In [ ]:
Explanation:

- axis=1 combines the DataFrames horizontally
- The Name column comes from df1
- The Salary column comes from df2
- Pandas aligns rows by their index labels

Important: concat(axis=1) matches rows by index, not automatically by employee name. Make sure the index alignment is correct before combining related columns.

In [4]:
import pandas as pd                     #Combining Data frames with Different columns

df1 = pd.DataFrame({
    "Name": ["Ravi", "Priya"],
    "Salary": [30000, 40000]
})

df2 = pd.DataFrame({
    "Name": ["Kiran", "Sneha"],
    "Department": ["IT", "HR"]
})

result = pd.concat(
    [df1, df2],
    ignore_index=True
)

print(result)

    Name   Salary Department
0   Ravi  30000.0        NaN
1  Priya  40000.0        NaN
2  Kiran      NaN         IT
3  Sneha      NaN         HR

In [ ]:
Why does NaN appear?

- df1 has a Salary column but no Department column
- df2 has a Department column but no Salary column
- With the default join="outer", Pandas keeps all columns
- Missing values are represented by NaN
                       
This is useful when combining reports that do not contain exactly the same columns

## merge()

In [ ]:
The Pandas merge() function is used to combine two DataFrames based on one or more common columns or keys

For example, imagine you have two tables:
    
- Customers: contains customer IDs, names, and cities
- Orders: contains order IDs, customer IDs, and order amounts

Both tables have a common column called Customer_ID. You can use merge() to combine customer details with their orders

Real-world applications:
    
- Combining customer information with purchase records
- Joining employee details with department information
- Combining product details with sales data
- Preparing datasets for data analysis and machine learning

Syntax:

    pd.merge(
    left,
    right,
    how="inner",
    on=None,
    left_on=None,
    right_on=None
)

    Parameter	Meaning
    
   left	     The first DataFrame
   right	 The second DataFrame
   how	     Specifies the type of join
   on	     Common column name in both DataFrames
 left_on	 Key column in the left DataFrame
 right_on	 Key column in the right DataFrame
    
The most important parameter is how, which determines which rows are retained in the result

AI/ML data preparation:
    
- Combine feature tables using customer or transaction IDs
- Join labels to training examples
- Connect product information with historical sales
- Enrich a dataset with related attributes before analysis
    
Always ensure that your join keys represent the intended relationship; an incorrect merge can create duplicate rows or misleading results.

In [5]:
import pandas as pd                    #Example

customers = pd.DataFrame({
    "Customer_ID": [101, 102, 103, 104],
    "Name": ["Ravi", "Priya", "Kiran", "Sneha"],
    "City": ["Hyderabad", "Chennai", "Mumbai", "Delhi"]
})

orders = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004],
    "Customer_ID": [101, 102, 101, 103],
    "Amount": [500, 800, 300, 1000]
})

print("Customers:")
print(customers)

print("\nOrders:")
print(orders)

Customers:
   Customer_ID   Name       City
0          101   Ravi  Hyderabad
1          102  Priya    Chennai
2          103  Kiran     Mumbai
3          104  Sneha      Delhi

Orders:
   Order_ID  Customer_ID  Amount
0      1001          101     500
1      1002          102     800
2      1003          101     300
3      1004          103    1000

In [6]:
result = pd.merge(                      #Merge Using Customer_ID
    customers,
    orders,
    on="Customer_ID"
)

print(result)

   Customer_ID   Name       City  Order_ID  Amount
0          101   Ravi  Hyderabad      1001     500
1          101   Ravi  Hyderabad      1003     300
2          102  Priya    Chennai      1002     800
3          103  Kiran     Mumbai      1004    1000

In [ ]:
Types of Joins in merge()

Pandas supports four common join types:

- inner — only matching records
- left — all records from the left DataFrame
- right — all records from the right DataFrame
- outer — all records from both DataFrames

In [7]:
pd.merge(customers, orders, on="Customer_ID", how="inner")     #Inner Join

   Customer_ID   Name       City  Order_ID  Amount
0          101   Ravi  Hyderabad      1001     500
1          101   Ravi  Hyderabad      1003     300
2          102  Priya    Chennai      1002     800
3          103  Kiran     Mumbai      1004    1000

In [ ]:
Returns only customer IDs that appear in both DataFrames

Result: customers 101, 102, and 103, with their matching orders

In [8]:
pd.merge(customers, orders, on="Customer_ID", how="left")         #Left Join

   Customer_ID   Name       City  Order_ID  Amount
0          101   Ravi  Hyderabad    1001.0   500.0
1          101   Ravi  Hyderabad    1003.0   300.0
2          102  Priya    Chennai    1002.0   800.0
3          103  Kiran     Mumbai    1004.0  1000.0
4          104  Sneha      Delhi       NaN     NaN

In [ ]:
Keeps every customer, even if they have no order

Result: Sneha remains in the output, with missing order values (NaN)

In [9]:
pd.merge(customers, orders, on="Customer_ID", how="right")        #Right Join

   Customer_ID   Name       City  Order_ID  Amount
0          101   Ravi  Hyderabad      1001     500
1          102  Priya    Chennai      1002     800
2          101   Ravi  Hyderabad      1003     300
3          103  Kiran     Mumbai      1004    1000

In [ ]:
Keeps every order, including orders without a matching customer record

Result: all rows from the orders DataFrame are retained

In [10]:
pd.merge(customers, orders, on="Customer_ID", how="outer")         #Outer Join

   Customer_ID   Name       City  Order_ID  Amount
0          101   Ravi  Hyderabad    1001.0   500.0
1          101   Ravi  Hyderabad    1003.0   300.0
2          102  Priya    Chennai    1002.0   800.0
3          103  Kiran     Mumbai    1004.0  1000.0
4          104  Sneha      Delhi       NaN     NaN

In [ ]:
Keeps all customer records and all order records, whether they match or not
    
Result: unmatched records are retained with missing values in the columns without matching data

## join()

In [ ]:
In Pandas, the join() method is used to combine two DataFrames based on their index by default

It helps us bring related information from two different DataFrames into a single DataFrame

For example, suppose we have two tables:
    
- Students DataFrame: Student ID and name
- Marks DataFrame: Student ID and marks
    
We can use join() to combine student names and their marks into one table

In [15]:
students = pd.DataFrame({             #Dataframe1
    "Name": ["Ajay", "Vijay", "Bunny"],
    "Age": [21, 22, 20]
}, index=[1, 2, 3])

print(students)

    Name  Age
1   Ajay   21
2  Vijay   22
3  Bunny   20

In [12]:
marks = pd.DataFrame({                   #Dataframe2
    "Marks": [85, 90, 78]
}, index=[1, 2, 3])

print(marks)

   Marks
1     85
2     90
3     78

In [16]:
result = students.join(marks)         #Using join

print(result)

    Name  Age  Marks
1   Ajay   21     85
2  Vijay   22     90
3  Bunny   20     78

In [ ]:
Explanation:

- students contains names and ages
- marks contains marks
- join() matches the rows using their index values
- The resulting DataFrame contains all three columns: Name, Age, and Marks

In [17]:
students.join(marks, how="left")             #Left Join

    Name  Age  Marks
1   Ajay   21     85
2  Vijay   22     90
3  Bunny   20     78

In [ ]:
Keeps every row from the left DataFrame (students) and adds matching information from the right DataFrame (marks)

In [18]:
students.join(marks, how="inner")       #Innerjoin

    Name  Age  Marks
1   Ajay   21     85
2  Vijay   22     90
3  Bunny   20     78

In [ ]:
Keeps only index values present in both DataFrames

In [19]:
students.join(marks, how="right")       #Right Join

    Name  Age  Marks
1   Ajay   21     85
2  Vijay   22     90
3  Bunny   20     78

In [ ]:
Keeps every row from the right DataFrame (marks)

In [20]:
students.join(marks, how="outer")     #OuterJoin

    Name  Age  Marks
1   Ajay   21     85
2  Vijay   22     90
3  Bunny   20     78

In [ ]:
Keeps all index values from both DataFrames. Missing matching values appear as NaN

## append()

In [ ]:
The append() method was previously used to add rows from one DataFrame to another DataFrame

For example, suppose you have student records in two DataFrames. You want to combine them into one DataFrame. Earlier, you could use append()

Important: DataFrame.append() was deprecated in Pandas 1.4.0 and removed in Pandas 2.0.0. In modern Pandas, use pd.concat() instead

Why was append() deprecated?

Pandas deprecated DataFrame.append() and Series.append() in version 1.4.0 and removed them in version 2.0.0. The recommended alternative is pd.concat(). 

The main reasons are:
1. Redundant functionality: pd.concat() already performs the same row-combining operation.
2. Performance: Repeatedly appending rows can be inefficient because a new combined object is produced each time.
3. Simpler API: One function, pd.concat(), can combine two or more DataFrames and Series.
The key point is that append() was not removed because combining rows is no longer possible. The functionality is still available through pd.concat()

Alternative 1: Use pd.concat() to replace append()

In [21]:
import pandas as pd                   #Example

df1 = pd.DataFrame({
    "Name": ["Ravi", "Sita"],
    "Marks": [85, 90]
})

df2 = pd.DataFrame({
    "Name": ["Rahul", "Priya"],
    "Marks": [78, 95]
})

result = pd.concat([df1, df2])

print(result)

    Name  Marks
0   Ravi     85
1   Sita     90
0  Rahul     78
1  Priya     95

In [ ]:
Explanation:

- pd.concat() combines Pandas objects
- [df1, df2] is the list of DataFrames to combine
- By default, axis=0, so rows are combined vertically
- The original index labels are preserved by default

In [ ]:
Alternative 2: Add a single row to a DataFrame

In [22]:
df = pd.DataFrame({
    "Name": ["Ravi", "Sita"],
    "Marks": [85, 90]
})

new_row = pd.DataFrame([{
    "Name": "Rahul",
    "Marks": 78
}])

result = pd.concat(
    [df, new_row],
    ignore_index=True
)

print(result)

    Name  Marks
0   Ravi     85
1   Sita     90
2  Rahul     78

In [ ]:
Explanation:

1. df contains the existing student records
2. new_row creates a DataFrame containing one new record
3. pd.concat() combines the two DataFrames
4. ignore_index=True resets the index

In [ ]:
Alternative 3: Combine multiple DataFrames
You do not need to call append() repeatedly to combine multiple DataFrames. You can pass all of them to pd.concat() at once

In [23]:
df1 = pd.DataFrame({
    "Name": ["Ravi"],
    "Marks": [85]
})

df2 = pd.DataFrame({
    "Name": ["Sita"],
    "Marks": [90]
})

df3 = pd.DataFrame({
    "Name": ["Rahul"],
    "Marks": [78]
})

result = pd.concat(
    [df1, df2, df3],
    ignore_index=True
)

print(result)

    Name  Marks
0   Ravi     85
1   Sita     90
2  Rahul     78

In [ ]:
This approach is useful when combining data from multiple CSV files, monthly sales reports, or datasets collected from different sources

In [ ]:
Alternative 4: Add many rows efficiently

In [24]:
df = pd.DataFrame({
    "Name": ["Ravi"],
    "Marks": [85]
})

new_students = [
    {"Name": "Sita", "Marks": 90},
    {"Name": "Rahul", "Marks": 78},
    {"Name": "Priya", "Marks": 95}
]

result = pd.concat(
    [df, pd.DataFrame(new_students)],
    ignore_index=True
)

print(result)

    Name  Marks
0   Ravi     85
1   Sita     90
2  Rahul     78
3  Priya     95

In [ ]:
This is a better approach when processing large numbers of records. The Pandas documentation recommends collecting rows
and concatenating them together instead of repeatedly appending individual rows

## combine_first()

In [ ]:
The combine_first() method is used to fill missing values (NaN) in one DataFrame or Series using values from another DataFrame or Series

It works by:
    
- Keeping existing non-missing values from the first DataFrame
- Filling its missing values with matching non-missing values from the second DataFrame
- Aligning rows and columns by their index and column labels

Example: If a student's marks are missing in one DataFrame but available in another, combine_first() can fill in the missing marks


Syntax:

DataFrame.combine_first(other)

Parameter	Meaning

other	The DataFrame used to fill missing values in the original DataFrame

The method returns a new DataFrame. It does not modify the original DataFrame directly

In [25]:
df1 = pd.DataFrame({                      #Example #Dataframe1
    "Name": ["Ravi", "Sita", "Rahul"],
    "Marks": [85, None, 78]
}, index=[1, 2, 3])

print(df1)                              #Sita marks are missing

    Name  Marks
1   Ravi   85.0
2   Sita    NaN
3  Rahul   78.0

In [26]:
df2 = pd.DataFrame({                     #Dataframe2
    "Name": ["Ravi", "Sita", "Rahul"],
    "Marks": [80, 90, 88]
}, index=[1, 2, 3])

print(df2)

    Name  Marks
1   Ravi     80
2   Sita     90
3  Rahul     88

In [27]:
result = df1.combine_first(df2)               #Applying Combine first()

print(result)

    Name  Marks
1   Ravi   85.0
2   Sita   90.0
3  Rahul   78.0

In [ ]:
Explanation:

Student	df1marks	df2marks	Finalmarks
Ravi	  85	      80	      85
Sita	Missing	      90	      90
Rahul	  78	      88	      78

Ravi's marks remain 85, even though df2 contains 80. The method uses the second DataFrame only where the first DataFrame has missing values

In [28]:
employees_a = pd.DataFrame({                 #Realworld Business Example
    "Employee": ["Vijay", "Bunny", "Ajay"],
    "Salary": [30000, None, 40000]
}, index=[101, 102, 103])

employees_b = pd.DataFrame({
    "Salary": [32000, 35000, 42000]
}, index=[101, 102, 103])

final_employees = employees_a.combine_first(employees_b)

print(final_employees)

    Employee   Salary
101    Vijay  30000.0
102    Bunny  35000.0
103     Ajay  40000.0