# Notebook 13 – Missing Values

## isnull()

In Pandas, isnull() is used to identify missing values in a Series or DataFrame

Missing values may appear as:

- NaN — Not a Number
- None — Python's missing value
- NaT — Missing date or time value
- 
Simple meaning: isnull() checks whether a value is missing

- Returns True if the value is missing
- Returns False if the value is present

Business example: A company can use isnull() to identify missing customer ages, salaries, or email addresses before analyzing its data

AI/ML example: Before training a machine learning model, you can use isnull() to identify missing feature values that may need to be filled or handled

In [2]:
import pandas as pd                 #Example
import numpy as np

data = {
    "Name": ["Ajay", "Vijay", None, "Bunny"],
    "Age": [25, np.nan, 30, 28]
}

df = pd.DataFrame(data)

print(df)

    Name   Age
0   Ajay  25.0
1  Vijay   NaN
2    NaN  30.0
3  Bunny  28.0

In [3]:
print(df.isnull())          #Applying isnull() to a DataFrame

    Name    Age
0  False  False
1  False   True
2   True  False
3  False  False

In [ ]:
Explanation:

Index	Name	Age
  0	   False	False
  1	   False	True
  2	   True	    False
  3	   False	False

- True means the value is missing
- False means the value is available

In [4]:
print(df["Age"].isnull())       #Checking missing values in a single column

0    False
1     True
2    False
3    False
Name: Age, dtype: bool

In [5]:
print(df.isnull().sum())          #Counting missing values using sum()

Name    1
Age     1
dtype: int64

In [ ]:
Explanation:

- isnull() identifies missing values
- sum() counts the True values in each column as 1

Therefore, both Name and Age contain one missing value each

In [6]:
print(df.isnull().sum().sum())             #To count all missing values in the entire DataFrame

2

In [8]:
import pandas as pd                #Real-world example: Student dataset
import numpy as np

students = pd.DataFrame({
    "Student": ["Ajay", "Vijay", "Bunny", "Sai"],
    "Maths": [85, np.nan, 78, 92],
    "Science": [90, 88, np.nan, 95]
})

print(students)
print("\nMissing values:")
print(students.isnull().sum())

  Student  Maths  Science
0    Ajay   85.0     90.0
1   Vijay    NaN     88.0
2   Bunny   78.0      NaN
3     Sai   92.0     95.0

Missing values:
Student    0
Maths      1
Science    1
dtype: int64

## notnull()

In Pandas, notnull() is used to identify values that are not missing in a Series or DataFrame

Simple meaning: It checks whether a value is available or present

- Returns True if the value is present
- Returns False if the value is missing (NaN, None, or NaT)

AI/ML: Select records with available target labels before training a supervised learning model

In [9]:
import pandas as pd                  #Example
import numpy as np

data = {
    "Name": ["Ravi", "Raju", None, "Sita"],
    "Age": [25, np.nan, 30, 28]
}

df = pd.DataFrame(data)

print(df)

   Name   Age
0  Ravi  25.0
1  Raju   NaN
2   NaN  30.0
3  Sita  28.0

In [10]:
print(df.notnull())         #Applying notnull() to a DataFrame

    Name    Age
0   True   True
1   True  False
2  False   True
3   True   True

In [ ]:
Explanation:

Index	Name	Age

  0	   True	   True
  1	   True	   False
  2	   False   True
  3	   True	   True

For example, at index 1, the age is missing, so notnull() returns False

In [11]:
print(df["Age"].notnull())       #Checking a single column

0     True
1    False
2     True
3     True
Name: Age, dtype: bool

In [12]:
print(df.notnull().sum())         #Counting available values

Name    3
Age     3
dtype: int64

In [ ]:
Explanation:

- Name contains 3 available values
- Age contains 3 available values
- Missing values are not counted because they return False

In [13]:
print(df.notnull().sum().sum())    #To count all available cells in the DataFrame

6

In [14]:
students = pd.DataFrame({                   #Filtering rows using notnull()
    "Name": ["Ajay", "Vijay", "Bunny", "Sai"],
    "Age": [22, np.nan, 25, np.nan]
})

result = students[students["Age"].notnull()]

print(result)

    Name   Age
0   Ajay  22.0
2  Bunny  25.0

In [ ]:
How it works:
    
1. students["Age"].notnull() checks each age
2. It returns True for rows with an age and False for missing ages
3. students[...] keeps only rows where the condition is True

## dropna()

In Pandas, dropna() is used to remove rows or columns that contain missing values such as NaN, None, or NaT

Simple meaning: If your dataset has missing values, dropna() helps you remove the affected rows or columns

For example, in a student dataset, if a student's marks are missing, you can remove that row using dropna()

Syntax:

DataFrame.dropna(
    axis=0,
    how="any",
    thresh=None,
    subset=None,
    inplace=False
)


Parameter	Meaning

axis=0	    Remove rows (default).
axis=1	    Remove columns.
how="any"	Remove a row or column if at least one value is missing
how="all"	Remove a row or column only if all its values are missing
thresh	    Keep rows or columns with at least a specified number of non-missing values
subset	    Check only specified columns for missing values
inplace=True	Modify the original DataFrame instead of returning a separate result

AI/ML: Remove training records with missing target labels, or incomplete records when suitable for the model and dataset

In [15]:
import pandas as pd               #Remove rows containing missing values
import numpy as np

df = pd.DataFrame({
    "Name": ["Ajay", "Vijay", "Sai", "Bunny"],
    "Age": [25, np.nan, 30, 28],
    "Salary": [30000, 40000, np.nan, 50000]
})

print(df)

    Name   Age   Salary
0   Ajay  25.0  30000.0
1  Vijay   NaN  40000.0
2    Sai  30.0      NaN
3  Bunny  28.0  50000.0

In [16]:
result = df.dropna()                     #apply dropna()

print(result)

    Name   Age   Salary
0   Ajay  25.0  30000.0
3  Bunny  28.0  50000.0

In [ ]:
Explanation:

- Ajay's row remains because no values are missing
- Vijay's row is removed because Age is missing
- Sai's row is removed because Salary is missing
- Bunny's row remains because no values are missing

By default, dropna() uses axis=0 and how="any"

In [17]:
result = df.dropna(axis=1)      #Remove columns containing missing values

print(result)

    Name
0   Ajay
1  Vijay
2    Sai
3  Bunny

In [ ]:
Both Age and Salary contain missing values, so both columns are removed. The Name column has no missing values, so it remains

In [18]:
df2 = pd.DataFrame({               #Using how="all"
    "Name": ["Ajay", None, "Vijay"],
    "Age": [25, np.nan, 30],
    "Salary": [30000, np.nan, 40000]
})

result = df2.dropna(how="all")

print(result)

    Name   Age   Salary
0   Ajay  25.0  30000.0
2  Vijay  30.0  40000.0

In [ ]:
The second row is removed because all three values are missing

Compare the two options:
    
- how="any": Remove a row if at least one value is missing
- how="all": Remove a row only if all values are missing

## fillna()

In Pandas, fillna() is used to replace missing values (NaN, None, or NaT) with another value

For example, if a student’s marks are missing, you can replace the missing marks with 0, the average marks, or another suitable value

Simple meaning:

- dropna() → Removes rows or columns containing missing values
- fillna() → Fills missing values without removing the rows or columns

Syntax:

DataFrame.fillna(
    value=None,
    method=None,
    axis=None,
    inplace=False,
    limit=None
)

Parameter	    Meaning

value	       Value used to replace missing data.
method	   Strategy for filling from neighboring values in versions that support it; current Pandas uses methods such as ffill() and bfill() directly
axis	   Direction in which filling is applied
inplace=True	Modifies the original DataFrame
limit	    Limits the number of missing values filled in a consecutive run

In [19]:
import pandas as pd                    #Replace missing values with zero
import numpy as np

df = pd.DataFrame({
    "Name": ["Ajay", "Vijay", "Bunny", "Sai"],
    "Age": [25, np.nan, 30, np.nan],
    "Marks": [85, 90, np.nan, 95]
})

print(df)

    Name   Age  Marks
0   Ajay  25.0   85.0
1  Vijay   NaN   90.0
2  Bunny  30.0    NaN
3    Sai   NaN   95.0

In [20]:
result = df.fillna(0)           #replace all missing values with 0

print(result)

    Name   Age  Marks
0   Ajay  25.0   85.0
1  Vijay   0.0   90.0
2  Bunny  30.0    0.0
3    Sai   0.0   95.0

In [ ]:
Explanation:

- Vijay's missing age becomes 0
- Bunny's missing marks become 0
- sai's missing age becomes 0
- Other values remain unchanged

Note that replacing missing ages or marks with zero is only appropriate when zero has a meaningful interpretation

In [21]:
result = df.fillna({              #Filling missing values with different values for each column
    "Age": 18,
    "Marks": 0
})

print(result)

    Name   Age  Marks
0   Ajay  25.0   85.0
1  Vijay  18.0   90.0
2  Bunny  30.0    0.0
3    Sai  18.0   95.0

In [ ]:
Here:

- Missing Age values are replaced with 18
- Missing Marks values are replaced with 0

The Name column is unchanged

## interpolate()

In Pandas, interpolate() is used to fill missing values by estimating values from existing data points

It is especially useful for numerical data, time-series data, temperature readings, sales data, and sensor measurements

Simple meaning: Instead of replacing every missing value with zero or the mean, interpolate() estimates a value based on the surrounding values

For example, if the temperature is 20°C at 10 AM and 24°C at 12 PM, the estimated temperature at 11 AM is 22°C, assuming a linear change

Syntax:

DataFrame.interpolate(
    method="linear",
    axis=0,
    limit=None,
    limit_direction="forward",
    limit_area=None,
    inplace=False
)

Parameter	          Meaning

method="linear"	    Estimates values assuming equal spacing between observations
axis=0	            Interpolates down each column (default)
axis=1	            Interpolates across each row
limit	            Limits the number of consecutive missing values filled
limit_direction  	Controls the direction of filling
limit_area	        Restricts filling to inside or outside existing values
inplace=True	    Modifies the original DataFrame

In [22]:
import pandas as pd                #Simple example using a Series
import numpy as np

data = pd.Series([10, 20, np.nan, 40, 50])

print(data)

0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
dtype: float64

In [23]:
result = data.interpolate()           #use interpolate()

print(result)

0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
dtype: float64

How did Pandas calculate 30?

The missing value lies between 20 and 40

$$
\text{Missing value} = \frac{20 + 40}{2} = 30
$$

Therefore, Pandas estimates the missing value as 30.0

4. Linear interpolation formula

Linear interpolation estimates a value between two known data points.

$$
y = y_1 + \frac{x - x_1}{x_2 - x_1}(y_2 - y_1)
$$

Where:

- \(x_1,y_1\) are the first known point
- \(x_2,y_2\) are the second known point
- \(x\) is the position of the missing value
- \(y\) is the estimated value

For equally spaced observations, the formula simplifies to taking evenly spaced steps between the known values

In [24]:
data = pd.Series([10, np.nan, np.nan, 40])         #Example with multiple missing values

print(data.interpolate())

0    10.0
1    20.0
2    30.0
3    40.0
dtype: float64

In [25]:
df = pd.DataFrame({                     #Interpolation in a DataFrame
    "Maths": [60, np.nan, 80, 90],
    "Science": [70, 75, np.nan, 90]
})

print(df)

   Maths  Science
0   60.0     70.0
1    NaN     75.0
2   80.0      NaN
3   90.0     90.0

In [26]:
result = df.interpolate()        #Apply interpolation

print(result)

   Maths  Science
0   60.0     70.0
1   70.0     75.0
2   80.0     82.5
3   90.0     90.0

In [ ]:
Explanation:

- Maths: the missing value between 60 and 80 becomes 70
- Science: the missing value between 75 and 90 becomes 82.5
By default, interpolation works vertically through each column

## Missing Value Handling Strategies

Missing value handling is the process of identifying and managing values that are absent from a dataset

Missing values can occur because a user skips a form field, a sensor fails to record a measurement, or data is lost during collection or merging

In Pandas, missing values commonly appear as NaN, None, or NaT


Missing value handling in AI/ML

Missing values can affect model training and prediction. A typical workflow is:

1. Identify missing values using isnull().sum().
2. Understand why the values are missing.
3. Choose a suitable strategy for each feature.
4. Fit imputation rules using the training data only.
5. Apply the same rules to validation and test d

In [27]:
import pandas as pd                    #Example dataset
import numpy as np

df = pd.DataFrame({
    "Name": ["Ajay", "Vijay", "bunny", "Raju", "Arun"],
    "Age": [25, np.nan, 30, np.nan, 35],
    "Salary": [30000, 40000, np.nan, 50000, 60000]
})

print(df)                    #Here, the Age column has two missing values, and the Salary column has one missing value

    Name   Age   Salary
0   Ajay  25.0  30000.0
1  Vijay   NaN  40000.0
2  bunny  30.0      NaN
3   Raju   NaN  50000.0
4   Arun  35.0  60000.0

In [28]:
df.isnull()            #Identify missing values

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False   True   False
4  False  False   False

In [29]:
df.isnull().sum()          #Count missing values in each column

Name      0
Age       2
Salary    1
dtype: int64

In [30]:
df.dropna()                 #Remove missing values   #This removes rows containing at least one missing value by default

   Name   Age   Salary
0  Ajay  25.0  30000.0
4  Arun  35.0  60000.0